function check_laplace_action_rectangle
%CHECK_LAPLACE_ACTION_RECTANGLE Test the DST Laplace action on a known function.
%
%   Re-implements the original dst_laplace_grid_test script against the
%   refactored API: it applies the masked DST Laplace operator
%   (MAKE_DST_LAPLACE_OP) on the rectangle [0,pi] x [0,pi] to the analytic
%   function
%
%       u(x, y) = sin(mm*x) * sin(nn*y),
%
%   which vanishes on the boundary, and compares the result against its
%   exact Laplacian
%
%       laplace u(x, y) = -(mm^2 + nn^2) * u(x, y).
%
%   For a pure sine mode that fits the grid the DST second derivative is
%   exact, so the residual is at the level of floating-point round-off.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8).

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    % Domain [a, b] x [c, d] and grid resolution (M interior points per slice).
    a = 0; b = pi; c = 0; d = pi;
    M = 20;

    % Analytic test function and its exact Laplacian (vanishes on the boundary).
    mm = 5;
    nn = 1;
    u         = @(x, y) sin(mm*x) .* sin(nn*y);
    laplace_u = @(x, y) -(mm^2 + nn^2) * u(x, y);

    % Masked DST Laplace operator on the rectangle.
    indicator_function = @(x, y) indicator_rectangle(x, y, a, b, c, d);
    [dst_laplace_op, info] = make_dst_laplace_op([a b], [c d], M, indicator_function);

    % Gather the analytic values onto the degrees-of-freedom vector.
    u_grid = u(info.X, info.Y);
    u_vec  = vals_grid_to_vals_vec(u_grid, info.global_mask);

    % Numerical Laplacian (new API) vs. the exact Laplacian on the same DOFs.
    laplace_u_vec_num   = dst_laplace_op(u_vec);
    laplace_u_vec_exact = laplace_u(info.X, info.Y);
    laplace_u_vec_exact = vals_grid_to_vals_vec(laplace_u_vec_exact, info.global_mask);

    residual    = laplace_u_vec_exact - laplace_u_vec_num;
    norm_resid  = norm(residual);
    norm_exact  = norm(laplace_u_vec_exact);
    rel_resid   = norm_resid / norm_exact;

    fprintf('rectangle [0,pi]^2  M=%d  dofs=%d  mode (mm,nn)=(%d,%d)\n', ...
        M, info.dofs, mm, nn);
    fprintf('||laplace_u_exact - laplace_u_num||_2 = %.3e  (rel %.3e)\n', ...
        norm_resid, rel_resid);

    tol = 1e-10;
    if rel_resid > tol
        error('check_laplace_action_rectangle:tolExceeded', ...
            'Relative residual %.3e exceeds tolerance %.3e.', rel_resid, tol);
    end
    fprintf('PASS (rel residual %.3e <= tol %.3e)\n', rel_resid, tol);
end
