function [dst_laplace_op, info] = make_dst_laplace_op_batched(x_range, y_range, M, indicator_function)
%MAKE_DST_LAPLACE_OP_BATCHED Precompute-once sparse-backed DST Laplace operator.
%
%   [dst_laplace_op, info] = make_dst_laplace_op_batched(x_range, y_range, M, indicator_function)
%
%   Faster, better-scaling alternative to MAKE_DST_LAPLACE_OP. The original
%   operator redoes the whole DST sweep on every application: it allocates a
%   NaN grid, re-runs the contiguous-block decomposition on every slice, and
%   transforms every column and row inside a parfor. Because the domain mask
%   is fixed, all of that is constant across applications.
%
%   This factory instead assembles the Laplace matrix once via
%   MAKE_DST_LAPLACE_SPARSE and returns an operator that applies it. The
%   matrix is kept SPARSE: every degree of freedom only couples to the other
%   interior points in its own column block and row block, so the operator
%   has O(M^3) nonzeros rather than the O(M^4) of a dense matrix. Each
%   application is then a single sparse matrix-vector product -- no parfor,
%   no NaN grid, no per-call block decomposition.
%
%   The signature matches MAKE_DST_LAPLACE_OP; see that function for a
%   description of the inputs and the info struct. The returned operator is
%   numerically identical (up to round-off) and is symmetric, so it can be
%   used with eigs('IsFunctionSymmetric', true) exactly as before.
%
%   See also MAKE_DST_LAPLACE_SPARSE, MAKE_DST_LAPLACE_MAT_BATCHED,
%   MAKE_DST_LAPLACE_OP, DST_LAPLACE_GRID.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) as a
%   precompute-once version of the original MAKE_DST_LAPLACE_OP script.

    [L, info] = make_dst_laplace_sparse(x_range, y_range, M, indicator_function);

    dst_laplace_op = @(v) L * v;

end
