function [L, info] = make_dst_laplace_sparse(x_range, y_range, M, indicator_function)
%MAKE_DST_LAPLACE_SPARSE Assemble the DST-based Laplace matrix in sparse form.
%
%   [L, info] = make_dst_laplace_sparse(x_range, y_range, M, indicator_function)
%
%   Core assembly shared by MAKE_DST_LAPLACE_MAT_BATCHED (which densifies the
%   result) and MAKE_DST_LAPLACE_OP_BATCHED (which wraps it as a matvec). It
%   exploits the structure of DST_LAPLACE_GRID:
%
%     - DST_LAPLACE_GRID applies DST_D2_SLICE to every column (x-derivative)
%       and every row (y-derivative); DST_D2_SLICE in turn applies
%       DST_D2_CHUNK to every contiguous non-NaN (interior) block.
%     - On a block of N interior points, DST_D2_CHUNK is a *fixed* linear
%       map that depends only on N and h. Its matrix is
%         B_N = s * idst(kvec .* dst(eye(N))),  s = (pi/((N+1)h))^2,
%       computed in one shot because dst/idst act column-wise.
%     - The domain mask is the same for every basis vector, so the block
%       structure is fixed. The Laplace matrix is therefore the sum of the
%       per-block maps B_N scattered onto the global degrees of freedom:
%       column blocks for the x-derivative, row blocks for the y-derivative.
%
%   Every degree of freedom only couples to the other interior points in its
%   own column block and row block, so L has O(M^3) nonzeros (not the O(M^4)
%   of a dense matrix) and is returned sparse.
%
%   The signature matches MAKE_DST_LAPLACE_OP; see that function for a
%   description of the inputs and the info struct.
%
%   Outputs:
%     L    - info.dofs-by-info.dofs SPARSE matrix of the discrete Laplacian
%            on the degrees of freedom.
%     info - grid/domain struct returned by MAKE_DST_LAPLACE_OP.
%
%   See also MAKE_DST_LAPLACE_MAT_BATCHED, MAKE_DST_LAPLACE_OP_BATCHED,
%   MAKE_DST_LAPLACE_OP, DST_LAPLACE_GRID, DST_D2_CHUNK.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) as the
%   shared core of the batched/vectorised MAKE_DST_LAPLACE_MAT script.

    % Reuse the factory only for the grid/domain data (mask, h, dofs).
    [~, info] = make_dst_laplace_op(x_range, y_range, M, indicator_function);

    global_mask = info.global_mask;
    h           = info.h;
    dofs        = info.dofs;
    [m, n]      = size(global_mask);

    % Column-major DOF index of every interior grid point, 0 outside the
    % domain. This matches the ordering used by vals_grid_to_vals_vec
    % (logical indexing is column-major).
    dof_index = zeros(m, n);
    dof_index(global_mask) = 1:dofs;

    % Cache of 1-D DST second-derivative block matrices B_N, keyed by block
    % length N. The same matrix serves both the x- and y-direction because
    % the grid spacing h is equal in both directions.
    block_cache = containers.Map('KeyType', 'double', 'ValueType', 'any');

    % Sparse-assembly triplets, grown block by block.
    ii = {};
    jj = {};
    vv = {};

    % x-derivative: second derivative down each column. The interior points
    % of a column block occupy a consecutive DOF range.
    for j = 1:n
        [starts, ends] = mask_blocks(global_mask(:, j));
        for b = 1:numel(starts)
            d = dof_index(starts(b):ends(b), j);   % column vector, increasing
            [I, J, V] = block_triplets(d, block_matrix(numel(d), h, block_cache));
            ii{end+1} = I; jj{end+1} = J; vv{end+1} = V; %#ok<AGROW>
        end
    end

    % y-derivative: second derivative along each row. The interior points of
    % a row block map to scattered (but increasing) DOF indices.
    for i = 1:m
        [starts, ends] = mask_blocks(global_mask(i, :));
        for b = 1:numel(starts)
            d = dof_index(i, starts(b):ends(b)).';  % column vector, increasing
            [I, J, V] = block_triplets(d, block_matrix(numel(d), h, block_cache));
            ii{end+1} = I; jj{end+1} = J; vv{end+1} = V; %#ok<AGROW>
        end
    end

    % x- and y-contributions sharing a DOF pair are summed by sparse().
    L = sparse(vertcat(ii{:}), vertcat(jj{:}), vertcat(vv{:}), dofs, dofs);

end

% -------------------------------------------------------------------------

function [starts, ends] = mask_blocks(mask_slice)
%MASK_BLOCKS Start/end indices of contiguous true runs in a logical slice.
%   Same block detection as DST_D2_SLICE: pad with false on both sides and
%   look at the transitions of diff.
    mask_slice = mask_slice(:)';
    edges = diff([false, mask_slice, false]);
    starts = find(edges == 1);
    ends   = find(edges == -1) - 1;
end

% -------------------------------------------------------------------------

function B = block_matrix(N, h, block_cache)
%BLOCK_MATRIX DST second-derivative matrix for a block of N interior points.
%   B is the matrix of DST_D2_CHUNK: B(:,k) = dst_d2_chunk(e_k, h). Because
%   dst/idst act column-wise, the whole matrix is obtained by transforming
%   the identity in one call. Results are cached per length N.
    if isKey(block_cache, N)
        B = block_cache(N);
        return
    end
    s = (pi/((N + 1)*h))^2;
    kvec = -((1:N).^2)';
    B = s * idst(kvec .* dst(eye(N)));
    block_cache(N) = B;
end

% -------------------------------------------------------------------------

function [I, J, V] = block_triplets(d, B)
%BLOCK_TRIPLETS Sparse triplets adding the dense block B at DOF indices d.
%   Contribution L(d(r), d(c)) += B(r, c).
    [R, C] = ndgrid(d, d);
    I = R(:);
    J = C(:);
    V = B(:);
end

% -------------------------------------------------------------------------
% NOTES
% -------------------------------------------------------------------------
%
% What this file does
% -------------------
% It assembles the discrete Dirichlet Laplacian as an explicit SPARSE matrix
% L over the interior degrees of freedom (DOFs) of a masked domain. It is the
% shared core behind MAKE_DST_LAPLACE_MAT_BATCHED (which densifies L) and
% MAKE_DST_LAPLACE_OP_BATCHED (which wraps L as a matvec).
%
% The idea it exploits: the DST Laplacian acts as a 1-D second-derivative
% operator applied independently to every column (d^2/dx^2) and every row
% (d^2/dy^2), and within each line, separately on each contiguous run of
% interior points. On a run of N points that operator is a *fixed* dense NxN
% map depending only on N and the spacing h. So the whole Laplacian is just
% these small blocks scattered onto global DOF indices and summed -- exactly
% sparse triplet assembly. This gives L only ~O(M^3) nonzeros instead of
% O(M^4).
%
% Pipeline:
%   1. Pull global_mask, h, dofs from MAKE_DST_LAPLACE_OP (operator handle
%      discarded).
%   2. Build dof_index: column-major DOF number for each interior point.
%   3. For each column, then each row: MASK_BLOCKS finds contiguous interior
%      runs; BLOCK_TRIPLETS emits L(d_r,d_c) += B(r,c) for each run's DOFs.
%   4. One sparse(...) call sums coinciding x/y contributions into L.
%
% The containers.Map block cache
% ------------------------------
% The per-block matrix is produced by BLOCK_MATRIX(N, h, block_cache):
%
%     s    = (pi/((N+1)*h))^2;
%     kvec = -((1:N).^2)';
%     B    = s * idst(kvec .* dst(eye(N)));   % matrix of dst_d2_chunk, one shot
%
% Because dst/idst act column-wise, transforming eye(N) yields the entire NxN
% block in a single call rather than column by column.
%
% The cache wrapping it:
%   - Keyed by the block length N -- the size of one maximal contiguous
%     interior run in a column or row, *not* the full column.
%   - Lazy fill: on each run, isKey(block_cache, N) is checked; a hit returns
%     the stored B_N, a miss computes it once and stores it. So the cache
%     holds exactly the distinct run-lengths present in the domain -- nothing
%     in between.
%   - x/y sharing: the same B_N serves both the column (x) and row (y) loops,
%     because h is equal in both directions.
%   - How many entries in practice: geometry-dependent, but small. A rectangle
%     yields a *single* entry B_M reused for all 2M slices; an L-shape yields a
%     handful (two column heights + two row widths). The largest possible N is
%     bounded by ~M, but the cache never stores the full sequence 1..M -- only
%     the few lengths that actually occur.
%
% Net effect: the cache eliminates redundant recomputation of identical dense
% blocks -- the dominant cost -- turning assembly into "build each distinct
% block once, scatter many times", which is what makes the sparse build cheap
% enough to reach M = 191 in the manufactured-solution test without ever
% forming a dense matrix.
