function [L, info] = make_dst_laplace_mat_batched(x_range, y_range, M, indicator_function)
%MAKE_DST_LAPLACE_MAT_BATCHED Assemble the DST-based Laplace matrix without per-DOF loops.
%
%   [L, info] = make_dst_laplace_mat_batched(x_range, y_range, M, indicator_function)
%
%   Vectorised equivalent of MAKE_DST_LAPLACE_MAT. It produces the same
%   matrix L but avoids applying the operator dofs times: it assembles the
%   matrix from the fixed per-block DST second-derivative maps via
%   MAKE_DST_LAPLACE_SPARSE and returns it as a dense matrix.
%
%   The signature matches MAKE_DST_LAPLACE_OP / MAKE_DST_LAPLACE_MAT; see
%   those functions for a description of the inputs and the info struct.
%
%   Outputs:
%     L    - info.dofs-by-info.dofs matrix of the discrete Laplacian on the
%            degrees of freedom. Equal (up to floating-point round-off) to
%            the matrix returned by MAKE_DST_LAPLACE_MAT.
%     info - grid/domain struct returned by MAKE_DST_LAPLACE_OP.
%
%   See also MAKE_DST_LAPLACE_SPARSE, MAKE_DST_LAPLACE_OP_BATCHED,
%   MAKE_DST_LAPLACE_MAT, MAKE_DST_LAPLACE_OP, DST_LAPLACE_GRID.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) as a
%   batched/vectorised version of the original MAKE_DST_LAPLACE_MAT script.

    [L, info] = make_dst_laplace_sparse(x_range, y_range, M, indicator_function);

    % Return a dense matrix to match MAKE_DST_LAPLACE_MAT (e.g. for eig).
    L = full(L);

end
