function [L, info] = make_dst_laplace_mat_batched(x_range, y_range, M, indicator_function)
%MAKE_DST_LAPLACE_MAT_BATCHED Assemble the DST-based Laplace matrix without per-DOF loops.
%
%   [L, info] = make_dst_laplace_mat_batched(x_range, y_range, M, indicator_function)
%
%   Vectorised equivalent of MAKE_DST_LAPLACE_MAT. It produces the same
%   matrix L but avoids applying the operator dofs times. Instead it
%   exploits the structure of DST_LAPLACE_GRID:
%
%     - DST_LAPLACE_GRID applies DST_D2_SLICE to every column (x-derivative)
%       and every row (y-derivative); DST_D2_SLICE in turn applies
%       DST_D2_CHUNK to every contiguous non-NaN (interior) block.
%     - On a block of N interior points, DST_D2_CHUNK is a *fixed* linear
%       map that depends only on N and h. Its matrix is
%         B_N = s * idst(kvec .* dst(eye(N))),  s = (pi/((N+1)h))^2,
%       computed in one shot because dst/idst act column-wise.
%     - The domain mask is the same for every basis vector, so the block
%       structure is fixed. The Laplace matrix is therefore the sum of the
%       per-block maps B_N scattered onto the global degrees of freedom:
%       column blocks for the x-derivative, row blocks for the y-derivative.
%
%   The signature matches MAKE_DST_LAPLACE_OP / MAKE_DST_LAPLACE_MAT; see
%   those functions for a description of the inputs and the info struct.
%
%   Outputs:
%     L    - info.dofs-by-info.dofs matrix of the discrete Laplacian on the
%            degrees of freedom. Equal (up to floating-point round-off) to
%            the matrix returned by MAKE_DST_LAPLACE_MAT.
%     info - grid/domain struct returned by MAKE_DST_LAPLACE_OP.
%
%   See also MAKE_DST_LAPLACE_MAT, MAKE_DST_LAPLACE_OP, DST_LAPLACE_GRID,
%   DST_D2_SLICE, DST_D2_CHUNK.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) as a
%   batched/vectorised version of the original MAKE_DST_LAPLACE_MAT script.

    % Reuse the factory only for the grid/domain data (mask, h, dofs).
    [~, info] = make_dst_laplace_op(x_range, y_range, M, indicator_function);

    global_mask = info.global_mask;
    h           = info.h;
    dofs        = info.dofs;
    [m, n]      = size(global_mask);

    % Column-major DOF index of every interior grid point, 0 outside the
    % domain. This matches the ordering used by vals_grid_to_vals_vec
    % (logical indexing is column-major).
    dof_index = zeros(m, n);
    dof_index(global_mask) = 1:dofs;

    % Cache of 1-D DST second-derivative block matrices B_N, keyed by block
    % length N. The same matrix serves both the x- and y-direction because
    % the grid spacing h is equal in both directions.
    block_cache = containers.Map('KeyType', 'double', 'ValueType', 'any');

    % Sparse-assembly triplets, grown block by block.
    ii = {};
    jj = {};
    vv = {};

    % x-derivative: second derivative down each column. The interior points
    % of a column block occupy a consecutive DOF range.
    for j = 1:n
        [starts, ends] = mask_blocks(global_mask(:, j));
        for b = 1:numel(starts)
            d = dof_index(starts(b):ends(b), j);   % column vector, increasing
            [I, J, V] = block_triplets(d, block_matrix(numel(d), h, block_cache));
            ii{end+1} = I; jj{end+1} = J; vv{end+1} = V; %#ok<AGROW>
        end
    end

    % y-derivative: second derivative along each row. The interior points of
    % a row block map to scattered (but increasing) DOF indices.
    for i = 1:m
        [starts, ends] = mask_blocks(global_mask(i, :));
        for b = 1:numel(starts)
            d = dof_index(i, starts(b):ends(b)).';  % column vector, increasing
            [I, J, V] = block_triplets(d, block_matrix(numel(d), h, block_cache));
            ii{end+1} = I; jj{end+1} = J; vv{end+1} = V; %#ok<AGROW>
        end
    end

    % x- and y-contributions sharing a DOF pair are summed by sparse().
    L = sparse(vertcat(ii{:}), vertcat(jj{:}), vertcat(vv{:}), dofs, dofs);

    % Return a dense matrix to match MAKE_DST_LAPLACE_MAT (e.g. for eig).
    L = full(L);

end

% -------------------------------------------------------------------------

function [starts, ends] = mask_blocks(mask_slice)
%MASK_BLOCKS Start/end indices of contiguous true runs in a logical slice.
%   Same block detection as DST_D2_SLICE: pad with false on both sides and
%   look at the transitions of diff.
    mask_slice = mask_slice(:)';
    edges = diff([false, mask_slice, false]);
    starts = find(edges == 1);
    ends   = find(edges == -1) - 1;
end

% -------------------------------------------------------------------------

function B = block_matrix(N, h, block_cache)
%BLOCK_MATRIX DST second-derivative matrix for a block of N interior points.
%   B is the matrix of DST_D2_CHUNK: B(:,k) = dst_d2_chunk(e_k, h). Because
%   dst/idst act column-wise, the whole matrix is obtained by transforming
%   the identity in one call. Results are cached per length N.
    if isKey(block_cache, N)
        B = block_cache(N);
        return
    end
    s = (pi/((N + 1)*h))^2;
    kvec = -((1:N).^2)';
    B = s * idst(kvec .* dst(eye(N)));
    block_cache(N) = B;
end

% -------------------------------------------------------------------------

function [I, J, V] = block_triplets(d, B)
%BLOCK_TRIPLETS Sparse triplets adding the dense block B at DOF indices d.
%   Contribution L(d(r), d(c)) += B(r, c).
    [R, C] = ndgrid(d, d);
    I = R(:);
    J = C(:);
    V = B(:);
end
