function check_op_batched_equiv
%CHECK_OP_BATCHED_EQUIV Compare reference and sparse-backed Laplace operators.
%
%   Verifies that the operator returned by MAKE_DST_LAPLACE_OP_BATCHED
%   reproduces the action of the reference matrix-free MAKE_DST_LAPLACE_OP
%   across several domains, including non-rectangular ones whose slices split
%   into multiple interior blocks.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) to test
%   the precompute-once version of the original MAKE_DST_LAPLACE_OP script.

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    cases = {
        'rectangle',  [0 pi],   [0 pi],   20, @(x,y) indicator_rectangle(x,y,0,pi,0,pi)
        'L-shaped',   [-1 1],   [-1 1],   30, @(x,y) indicator_L_shaped(x,y,-1,0,1,-1,0,1)
        'H',          [-1 2],   [-2 1],   24, @(x,y) indicator_H_shaped(x,y)
    };

    rng(0);
    for c = 1:size(cases,1)
        name = cases{c,1};
        [Lop_ref,  info] = make_dst_laplace_op(        cases{c,2}, cases{c,3}, cases{c,4}, cases{c,5});
        Lop_batched      = make_dst_laplace_op_batched(cases{c,2}, cases{c,3}, cases{c,4}, cases{c,5});

        % Compare the action on a random batch of vectors.
        V = randn(info.dofs, 8);
        ref = zeros(size(V));
        bat = zeros(size(V));
        for k = 1:size(V,2)
            ref(:,k) = Lop_ref(V(:,k));
            bat(:,k) = Lop_batched(V(:,k));
        end
        err = norm(ref - bat, 'fro');
        rel = err / norm(ref, 'fro');
        fprintf('%-12s dofs=%5d  ||Lop_ref - Lop_batched||_F = %.3e  (rel %.3e)\n', ...
            name, info.dofs, err, rel);
    end
end
