function check_batched_timing
%CHECK_BATCHED_TIMING Time loop-based vs batched Laplace-matrix builders.
%
%   Builds the discrete Laplace matrix on an L-shaped domain with both
%   MAKE_DST_LAPLACE_MAT and MAKE_DST_LAPLACE_MAT_BATCHED and reports the
%   wall-clock times, the speed-up, and the (round-off) difference.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) to test
%   the batched/vectorised version of the original MAKE_DST_LAPLACE_MAT script.

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    phi = @(x,y) indicator_Lshape(x,y,-1,0,1,-1,0,1);
    M = 60;

    tic;
    Lloop = make_dst_laplace_mat([-1 1], [-1 1], M, phi);
    t_loop = toc;

    tic;
    Lbatch = make_dst_laplace_mat_batched([-1 1], [-1 1], M, phi);
    t_batch = toc;

    fprintf('dofs=%d  loop=%.2fs  batched=%.3fs  speedup=%.0fx  err=%.2e\n', ...
        size(Lloop,1), t_loop, t_batch, t_loop/t_batch, norm(Lloop - Lbatch, 'fro'));
end
