function check_batched_equiv
%CHECK_BATCHED_EQUIV Compare loop-based and batched Laplace-matrix builders.
%
%   Verifies that MAKE_DST_LAPLACE_MAT_BATCHED reproduces the matrix of
%   MAKE_DST_LAPLACE_MAT across several domains, including non-rectangular
%   ones whose slices split into multiple interior blocks.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) to test
%   the batched/vectorised version of the original MAKE_DST_LAPLACE_MAT script.

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    cases = {
        'rectangle',  [0 pi],   [0 pi],   20, @(x,y) indicator_rectangle(x,y,0,pi,0,pi)
        'L-shaped',   [-1 1],   [-1 1],   30, @(x,y) indicator_L_shaped(x,y,-1,0,1,-1,0,1)
        'H',          [-1 2],   [-2 1],   24, @(x,y) indicator_H(x,y)
    };

    for c = 1:size(cases,1)
        name = cases{c,1};
        [Lloop, info]  = make_dst_laplace_mat(cases{c,2}, cases{c,3}, cases{c,4}, cases{c,5});
        Lbatch         = make_dst_laplace_mat_batched(cases{c,2}, cases{c,3}, cases{c,4}, cases{c,5});
        err = norm(Lloop - Lbatch, 'fro');
        rel = err / norm(Lloop, 'fro');
        fprintf('%-12s dofs=%5d  ||L_loop - L_batch||_F = %.3e  (rel %.3e)\n', ...
            name, info.dofs, err, rel);
    end
end
