function check_op_batched_timing
%CHECK_OP_BATCHED_TIMING Time the DST Laplace operator variants per apply.
%
%   On an L-shaped domain, compares the per-application cost of
%     (a) the reference matrix-free MAKE_DST_LAPLACE_OP,
%     (b) a precomputed dense matrix applied as L*v
%         (from MAKE_DST_LAPLACE_MAT_BATCHED), and
%     (c) the precompute-once sparse-backed MAKE_DST_LAPLACE_OP_BATCHED,
%   at increasing resolution M, and reports the speed-ups over (a).
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8) to test
%   the precompute-once version of the original MAKE_DST_LAPLACE_OP script.

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    phi = @(x,y) indicator_Lshape(x,y,-1,0,1,-1,0,1);
    reps = 50;

    rng(0);
    for M = [60 120]
        [Lop_ref, info] = make_dst_laplace_op(        [-1 1], [-1 1], M, phi);
        L               = make_dst_laplace_mat_batched([-1 1], [-1 1], M, phi);
        Lop_batched     = make_dst_laplace_op_batched( [-1 1], [-1 1], M, phi);
        dofs = info.dofs;

        v = randn(dofs, 1);
        ref = Lop_ref(v);
        dns = L * v;
        bat = Lop_batched(v);

        tic; for r = 1:reps, y = Lop_ref(v);     end; t_ref = toc/reps; %#ok<NASGU>
        tic; for r = 1:reps, y = L * v;          end; t_dns = toc/reps; %#ok<NASGU>
        tic; for r = 1:reps, y = Lop_batched(v); end; t_bat = toc/reps; %#ok<NASGU>

        fprintf(['M=%-4d dofs=%6d  ref=%.3es  dense=%.3es (%.0fx)  ' ...
                 'sparse=%.3es (%.0fx)  err=%.2e\n'], ...
            M, dofs, t_ref, t_dns, t_ref/t_dns, t_bat, t_ref/t_bat, ...
            norm(ref - bat));
    end
end
