function check_bvp_L_shaped_matfree
%CHECK_BVP_L_SHAPED_MATFREE Matrix-free MMS BVP test on the L-shape.
%
%   Matrix-free counterpart of CHECK_BVP_L_SHAPED: it solves the same
%   method-of-manufactured-solutions boundary value problem on the L-shaped
%   domain, but without ever assembling the Laplace matrix. Instead of the
%   sparse matrix from MAKE_DST_LAPLACE_SPARSE and a direct solve, it uses
%   the operator handle from MAKE_DST_LAPLACE_OP and a Krylov iterative
%   solver (conjugate gradients).
%
%   The discrete Dirichlet Laplacian is symmetric but NEGATIVE definite, so
%   -dst_laplace_op is symmetric positive definite. The problem
%
%       L u_vec = f_vec
%
%   is therefore solved as the SPD system (-L) u_vec = (-f_vec) with PCG.
%   The PCG residual tolerance is kept well below the O(h^2) discretisation
%   error so the iterative-solver error does not pollute the convergence
%   order or the monotone error decrease that the test checks.
%
%   As in CHECK_BVP_L_SHAPED, the manufactured solution is the polynomial
%
%       u(x, y) = x (x - pi)(x - b) * y (y - pi)(y - e),
%
%   whose factors vanish on the lines x = 0, b, pi and y = 0, e, pi that
%   make up the L-shaped boundary, so u = 0 there as required. The test
%   passes when the error decreases monotonically under refinement and the
%   finest grid is sufficiently accurate.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8).

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    % L-shaped domain corners.
    a = 0; c = pi; d = 0; f = pi;

    % Grid resolutions; M+1 must be divisible by 4 so the reentrant-corner
    % coordinates b = (M+1)/2 * h and e = (M+1)/4 * h land on grid lines.
    M_list  = [23 47 95 191];     % h halves between successive entries
    max_err = zeros(size(M_list));
    rel_err = zeros(size(M_list));

    % PCG residual tolerance. It must be small enough that the solver's
    % solution error stays well below the O(h^2) discretisation error, but
    % not below the unpreconditioned-CG round-off floor (~ cond(L)*eps, and
    % cond(L) grows like 1/h^2), or PCG stagnates. With cond(L) ~ 3e3 at the
    % finest grid, tol = 1e-10 gives a solution error ~3e-7, far below the
    % ~1.5e-4 discretisation error, while staying above the round-off floor.
    pcg_tol = 1e-10;

    fprintf('L-shaped domain, manufactured solution u = x(x-pi)(x-b) y(y-pi)(y-e)\n');
    fprintf('matrix-free solve via PCG on the SPD system (-L) u = (-f)\n');
    fprintf('%5s %7s %12s %12s %8s %6s\n', 'M', 'dofs', 'max_err', 'rel_err', 'order', 'iters');
    for k = 1:numel(M_list)
        M = M_list(k);
        h = (c - a) / (M + 1);
        b = (M + 1) / 2 * h;
        e = (M + 1) / 4 * h;

        indicator_function = @(x, y) indicator_L_shaped(x, y, a, b, c, d, e, f);
        [dst_laplace_op, info] = make_dst_laplace_op([a c], [d f], M, indicator_function);

        % Manufactured solution and its exact Laplacian laplace u = u_xx + u_yy.
        u         = @(x, y) x .* (x - pi) .* (x - b) .* y .* (y - pi) .* (y - e);
        laplace_u = @(x, y) 2 * (3*x - pi - b) .* y .* (y - pi) .* (y - e) ...
                          + 2 * (3*y - pi - e) .* x .* (x - pi) .* (x - b);

        u_vec_exact = vals_grid_to_vals_vec(u(info.X, info.Y), info.global_mask);
        f_vec       = vals_grid_to_vals_vec(laplace_u(info.X, info.Y), info.global_mask);

        % Solve the SPD system (-L) u_vec = (-f_vec) matrix-free with PCG and
        % compare against the manufactured solution.
        maxit = 10 * info.dofs;
        [u_vec_num, flag, ~, iter] = pcg(@(v) -dst_laplace_op(v), -f_vec, pcg_tol, maxit);
        if flag ~= 0
            error('check_bvp_L_shaped_matfree:pcgFailed', ...
                'PCG did not converge at M=%d (flag=%d).', M, flag);
        end

        err        = u_vec_num - u_vec_exact;
        max_err(k) = max(abs(err));
        rel_err(k) = max_err(k) / max(abs(u_vec_exact));

        if k == 1
            order = NaN;
        else
            order = log2(max_err(k-1) / max_err(k));   % h halves each step
        end
        fprintf('%5d %7d %12.3e %12.3e %8.2f %6d\n', ...
            M, info.dofs, max_err(k), rel_err(k), order, iter);
    end

    % Pass criteria: monotone decrease under refinement and an accurate finest grid.
    decreasing = all(diff(max_err) < 0);
    tol_fine   = 5e-4;
    if ~decreasing
        error('check_bvp_L_shaped_matfree:notConverging', ...
            'Max error does not decrease monotonically under refinement: [%s].', ...
            sprintf('%.3e ', max_err));
    end
    if rel_err(end) > tol_fine
        error('check_bvp_L_shaped_matfree:tolExceeded', ...
            'Finest-grid relative error %.3e exceeds tolerance %.3e.', rel_err(end), tol_fine);
    end
    fprintf('PASS (error decreases under refinement; finest rel error %.3e <= tol %.3e)\n', ...
        rel_err(end), tol_fine);
end

% -------------------------------------------------------------------------
% NOTE: unpreconditioned PCG is the wrong tool here
% -------------------------------------------------------------------------
%
% This matrix-free test is a demonstration, not a recommended solver. Plain
% PCG on the discrete Laplacian, with no preconditioner, is essentially
% useless at any serious resolution.
%
% A preconditioner is therefore essential to make a matrix-free solve
% competitive with the sparse direct solve in CHECK_BVP_L_SHAPED. A natural
% candidate is the fast discrete Green operator (the discrete inverse of the
% 1-D second-derivative operator that underlies this DST discretisation),
% which can be applied cheaply and used either as a preconditioner or as the
% building block of a direct tensor-product solver:
%
%   Blechta, Jan; Prusa, Vit; Trnka, Ladislav; Tuma, Karel.
%   "Fast construction of the discrete Green operator for a second order
%    ordinary differential equation." arXiv preprint arXiv:2412.06242 (2024).
