function check_bvp_L_shaped
%CHECK_BVP_L_SHAPED Method-of-manufactured-solutions BVP test on the L-shape.
%
%   Re-implements the original bvp_Lshaped_test script against the
%   refactored API, using the method of manufactured solutions: a known
%   function u that vanishes on the boundary of the L-shaped domain is
%   chosen, its exact Laplacian f = laplace u is formed analytically, and
%   the discrete Dirichlet problem
%
%       L u_vec = f_vec
%
%   is solved with the sparse DST Laplace matrix (MAKE_DST_LAPLACE_SPARSE).
%   The recovered solution is compared against the manufactured u on the
%   degrees of freedom.
%
%   Unlike a pure sine mode (which the DST differentiates exactly), the
%   polynomial manufactured solution carries a genuine discretisation
%   error, so the test is a convergence check: refining the grid must drive
%   the error down. It passes when the error decreases monotonically under
%   refinement and the finest grid is sufficiently accurate.
%
%   The manufactured solution is the polynomial
%
%       u(x, y) = x (x - pi)(x - b) * y (y - pi)(y - e),
%
%   whose factors vanish on the lines x = 0, b, pi and y = 0, e, pi that
%   make up the L-shaped boundary, so u = 0 there as required.
%
%   Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8).

    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'startup.m'));

    % L-shaped domain corners.
    a = 0; c = pi; d = 0; f = pi;

    % Grid resolutions; M+1 must be divisible by 4 so the reentrant-corner
    % coordinates b = (M+1)/2 * h and e = (M+1)/4 * h land on grid lines.
    M_list  = [23 47 95 191];     % h halves between successive entries
    max_err = zeros(size(M_list));
    rel_err = zeros(size(M_list));

    fprintf('L-shaped domain, manufactured solution u = x(x-pi)(x-b) y(y-pi)(y-e)\n');
    fprintf('%5s %7s %12s %12s %8s\n', 'M', 'dofs', 'max_err', 'rel_err', 'order');
    for k = 1:numel(M_list)
        M = M_list(k);
        h = (c - a) / (M + 1);
        b = (M + 1) / 2 * h;
        e = (M + 1) / 4 * h;

        indicator_function = @(x, y) indicator_L_shaped(x, y, a, b, c, d, e, f);
        [L, info] = make_dst_laplace_sparse([a c], [d f], M, indicator_function);

        % Manufactured solution and its exact Laplacian laplace u = u_xx + u_yy.
        u         = @(x, y) x .* (x - pi) .* (x - b) .* y .* (y - pi) .* (y - e);
        laplace_u = @(x, y) 2 * (3*x - pi - b) .* y .* (y - pi) .* (y - e) ...
                          + 2 * (3*y - pi - e) .* x .* (x - pi) .* (x - b);

        u_vec_exact = vals_grid_to_vals_vec(u(info.X, info.Y), info.global_mask);
        f_vec       = vals_grid_to_vals_vec(laplace_u(info.X, info.Y), info.global_mask);

        % Solve L u_vec = f_vec and compare against the manufactured solution.
        u_vec_num  = L \ f_vec;
        err        = u_vec_num - u_vec_exact;
        max_err(k) = max(abs(err));
        rel_err(k) = max_err(k) / max(abs(u_vec_exact));

        if k == 1
            order = NaN;
        else
            order = log2(max_err(k-1) / max_err(k));   % h halves each step
        end
        fprintf('%5d %7d %12.3e %12.3e %8.2f\n', M, info.dofs, max_err(k), rel_err(k), order);
    end

    % Pass criteria: monotone decrease under refinement and an accurate finest grid.
    decreasing = all(diff(max_err) < 0);
    tol_fine   = 5e-4;
    if ~decreasing
        error('check_bvp_L_shaped:notConverging', ...
            'Max error does not decrease monotonically under refinement: [%s].', ...
            sprintf('%.3e ', max_err));
    end
    if rel_err(end) > tol_fine
        error('check_bvp_L_shaped:tolExceeded', ...
            'Finest-grid relative error %.3e exceeds tolerance %.3e.', rel_err(end), tol_fine);
    end
    fprintf('PASS (error decreases under refinement; finest rel error %.3e <= tol %.3e)\n', ...
        rel_err(end), tol_fine);
end
