#!/usr/bin/env bash
#
# run_tests.sh — run every check_*.m test in this directory through MATLAB
# and write a human-readable markdown report.
#
# Usage:
#   ./run_tests.sh [report.md]
#
#   report.md   Optional output path (default: ./report.md next to this
#               script). MATLAB_BIN overrides the matlab executable.
#
# Exit status is non-zero if any test errors out.
#
# Generated by Claude (Claude Opus 4.8, model ID claude-opus-4-8).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPORT="${1:-$SCRIPT_DIR/report.md}"
MATLAB_BIN="${MATLAB_BIN:-matlab}"

if ! command -v "$MATLAB_BIN" >/dev/null 2>&1; then
    echo "Error: MATLAB ('$MATLAB_BIN') not found on PATH." >&2
    exit 1
fi

# Discover tests (functions named after their file).
shopt -s nullglob
tests=("$SCRIPT_DIR"/check_*.m)
shopt -u nullglob
if [ ${#tests[@]} -eq 0 ]; then
    echo "Error: no tests (check_*.m) found in $SCRIPT_DIR." >&2
    exit 1
fi

# Drop the parallel-pool start-up chatter MATLAB prints to stdout.
strip_noise() {
    grep -v -E 'parpool|parallel pool|Starting parallel|Connected to' || true
}

details_tmp="$(mktemp)"
trap 'rm -f "$details_tmp"' EXIT

declare -a names statuses durations
total_fail=0

for t in "${tests[@]}"; do
    fn="$(basename "$t" .m)"
    echo "Running $fn ..." >&2

    start=$(date +%s.%N)
    # Launch from the test directory so MATLAB finds the test function; each
    # test puts the project's own sources on the path via startup itself.
    if out="$(cd "$SCRIPT_DIR" && "$MATLAB_BIN" -batch "$fn" 2>&1)"; then
        status="✅ PASS"
    else
        status="❌ FAIL"
        total_fail=$((total_fail + 1))
    fi
    end=$(date +%s.%N)
    dur=$(awk "BEGIN{printf \"%.1f\", $end - $start}")

    out_clean="$(printf '%s\n' "$out" | strip_noise)"

    names+=("$fn")
    statuses+=("$status")
    durations+=("$dur")

    {
        echo "### \`$fn\`"
        echo
        echo "- Status: **$status**"
        echo "- Duration: ${dur}s"
        echo
        echo '```'
        printf '%s\n' "$out_clean"
        echo '```'
        echo
    } >> "$details_tmp"
done

# Assemble the report: header, summary table, then per-test details.
{
    echo "# Method of manufactured solutions — test report"
    echo
    echo "- Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "- Host: \`$(hostname)\`"
    echo "- Project root: \`$PROJECT_ROOT\`"
    echo "- MATLAB: \`$MATLAB_BIN\`"
    echo "- Tests run: ${#names[@]} (${total_fail} failed)"
    echo
    echo "## Summary"
    echo
    echo "| Test | Status | Duration |"
    echo "|------|--------|----------|"
    for i in "${!names[@]}"; do
        echo "| \`${names[$i]}\` | ${statuses[$i]} | ${durations[$i]}s |"
    done
    echo
    echo "## Details"
    echo
    cat "$details_tmp"
} > "$REPORT"

echo "Report written to $REPORT" >&2

[ "$total_fail" -eq 0 ] || exit 1
