function check_laplace_matrix_symmetry
%CHECK_LAPLACE_MATRIX_SYMMETRY Symmetry of the DST Laplace matrix, every domain.
%
%   The matrix assembled by MAKE_DST_LAPLACE_MAT_BATCHED is symmetric in exact
%   arithmetic: MAKE_DST_LAPLACE_SPARSE scatters each one-dimensional block map
%   onto the same index set in the row and the column direction, and the block
%   map B_N = s * idst(kvec .* dst(eye(N))) is itself symmetric. What the
%   assembled matrix carries is the rounding of the transforms, so ISSYMMETRIC
%   returns false -- it asks for bit-for-bit equality -- and EIG then takes the
%   general path, which is several times dearer than the symmetric one and
%   returns eigenvalues with small imaginary parts that the callers discard.
%
%   This test measures how far from symmetric the matrix actually is, on every
%   domain of DOMAIN_CATALOG_DST and at four resolutions each, and what the
%   symmetrisation (L + L')/2 is worth: it computes the spectrum both ways, times
%   both, and compares them eigenvalue by eigenvalue.
%
%   The table it prints carries, per domain and resolution:
%     - the relative asymmetry ||L - L'||_F / ||L||_F and the largest asymmetric
%       entry max|L - L'|,
%     - the largest imaginary part the general EIG produced,
%     - the time of each of the two spectra, and
%     - the largest difference between the two spectra.
%
%   Resolutions: four per domain, near M = 30, 60, 90 and 120, each chosen to
%   keep the domain edges on grid lines. The rule differs from domain to domain
%   and is stated with the values in RESOLUTION_PLAN.
%
%   The spectra are cached under spectra/ next to this file, one file per domain
%   and resolution holding both, so a re-run reports the same table without
%   recomputing anything. The timings of a cached row are those of the run that
%   produced the file. Delete the directory to measure again.
%
%   The test fails if any matrix has an asymmetric sparsity pattern, if the
%   relative asymmetry exceeds 1e-13 -- a hundred times what rounding produces --
%   or if symmetrising moves any eigenvalue by more than a relative 1e-8.
%
%   Generated by Claude Code (Claude Opus 5).

    here         = fileparts(mfilename('fullpath'));
    project_root = fileparts(fileparts(here));
    run(fullfile(project_root, 'startup.m'));
    addpath(fullfile(project_root, 'experiments'));   % domain_catalog_dst

    spectra_dir = fullfile(here, 'spectra');
    if ~exist(spectra_dir, 'dir')
        mkdir(spectra_dir);
    end

    REL_ASYMMETRY_TOL = 1e-13;
    REL_SPECTRUM_TOL  = 1e-8;

    plan = resolution_plan();
    if any(cellfun(@(m) numel(m), plan(:, 2)) ~= 4)
        error('check_laplace_matrix_symmetry:plan', ...
            'Every domain needs four resolutions.');
    end

    % Level by level rather than domain by domain, so that an interrupted run
    % leaves the cheap end of every domain in the cache rather than a few domains
    % complete and the rest missing.
    rows = empty_rows();
    for level = 1:4
        for i = 1:size(plan, 1)
            name = plan{i, 1};
            M    = plan{i, 2}(level);
            rows(end+1) = row_for(name, M, spectra_dir); %#ok<AGROW>
        end
    end

    print_table(rows, plan);
    verify(rows, REL_ASYMMETRY_TOL, REL_SPECTRUM_TOL);
end


function plan = resolution_plan()
%RESOLUTION_PLAN Four grid resolutions per domain, near 30, 60, 90 and 120.
%
%   A domain edge that falls between two grid lines is not seen by the
%   discretisation, and the alignment condition that avoids it is a condition on
%   M: the grid spacing is h = (width of the bounding box)/(M + 1), so an edge at
%   distance d from the left of the box needs d/h whole. Each row says what that
%   comes to for its domain.
%
%   The values below are the largest admissible ones at or below each target, so
%   that the four levels are comparable across domains.
    plan = { ...
        % domain                  M values          alignment condition
        'square',                 [30 60 90 120]; ...  % fills its box: none
        'rectangle',              [29 59 89 119]; ...  % M+1 even (edge y = pi)
        'isosceles_triangle',     [30 60 90 120]; ...  % hypotenuse y = x: none
        'small_rectangle',        [31 59 91 119]; ...  % M+1 divisible by 4 (pi/2, pi/4)
        'L_shaped',               [29 59 89 119]; ...  % M+1 even (corner at the origin)
        'ellipse_minus_quadrant', [31 59 91 119]; ...  % M+1 divisible by 4 (x = 0, y = 0)
        'H_shaped',               [29 59 89 119]; ...  % M+1 divisible by 3 (unit columns)
        'gww1',                   [29 59 89 119]; ...  % M+1 divisible by 6 (unit features)
        'gww2',                   [29 59 89 119]  ...  % M+1 divisible by 6
    };
end


function r = row_for(name, M, spectra_dir)
%ROW_FOR One line of the table, from the cache where there is one.
    path = fullfile(spectra_dir, sprintf('%s_M%d-eigenvalues.csv', name, M));
    r = read_cached(path);
    if ~isempty(r)
        fprintf('  %-24s M = %3d  cached\n', name, M);
        return;
    end

    c = domain_catalog_dst(name);
    [x_range, y_range] = bounding_box(c.box(1), c.box(2), c.box(3), c.box(4));
    fprintf('  %-24s M = %3d  assembling ...\n', name, M);
    [L, info] = make_dst_laplace_mat_batched(x_range, y_range, M, c.phi);

    A = L - L.';
    r = struct('name', name, 'M', M, 'dofs', info.dofs, ...
               'rel_asym', norm(A, 'fro') / norm(L, 'fro'), ...
               'max_asym', max(abs(A(:))), ...
               'pattern_sym', isequal((L ~= 0), (L.' ~= 0)), ...
               'issym', issymmetric(L), ...
               'max_imag', NaN, 't_general', NaN, 't_sym', NaN, ...
               'ev_general', [], 'ev_sym', []);

    % The two spectra, timed. Both are returned as eigenvalues of -Laplace,
    % ascending, which is the sign convention of the callers.
    t = tic;
    ev = eig(L);
    r.t_general = toc(t);
    r.max_imag  = max(abs(imag(ev)));
    r.ev_general = sort(-real(ev), 'ascend');

    S = (L + L.') / 2;
    t = tic;
    r.ev_sym = sort(-eig(S), 'ascend');
    r.t_sym  = toc(t);

    write_cached(path, r);
end


function verify(rows, rel_asymmetry_tol, rel_spectrum_tol)
%VERIFY The three claims the table is there to support.
    bad = ~[rows.pattern_sym];
    if any(bad)
        error('check_laplace_matrix_symmetry:pattern', ...
            'Asymmetric sparsity pattern on %s.', strjoin(labels(rows(bad)), ', '));
    end

    bad = [rows.rel_asym] > rel_asymmetry_tol;
    if any(bad)
        error('check_laplace_matrix_symmetry:asymmetry', ...
            'Relative asymmetry above %.0e on %s.', ...
            rel_asymmetry_tol, strjoin(labels(rows(bad)), ', '));
    end

    rel = arrayfun(@(r) max_rel_difference(r), rows);
    bad = rel > rel_spectrum_tol;
    if any(bad)
        error('check_laplace_matrix_symmetry:spectrum', ...
            'Symmetrising moved an eigenvalue by more than a relative %.0e on %s.', ...
            rel_spectrum_tol, strjoin(labels(rows(bad)), ', '));
    end

    [worst, iworst] = max(rel);
    where = labels(rows(iworst));
    fprintf(['\nEvery matrix is symmetric to rounding, its pattern exactly so, ', ...
             'and no\neigenvalue moves: the largest relative difference between ', ...
             'the two spectra\nis %.2e, on %s.\n'], worst, where{1});
end


function s = labels(rows)
    s = arrayfun(@(r) sprintf('%s (M = %d)', r.name, r.M), rows, ...
                 'UniformOutput', false);
end


function d = max_rel_difference(r)
%MAX_REL_DIFFERENCE The two spectra compared, relative to the eigenvalue.
%
%   Relative rather than absolute, the eigenvalues of one domain running over
%   four or five orders of magnitude from the ground state to the top of the
%   spectrum, and the top carrying the absolute difference whatever happens
%   lower down.
    d = max(abs(r.ev_general - r.ev_sym) ./ abs(r.ev_general));
end


function print_table(rows, plan)
%PRINT_TABLE The table, a block per domain, in the order of the plan.
    fprintf('\n%-24s %4s %6s  %10s %10s %10s %9s %9s %11s\n', ...
            'domain', 'M', 'dofs', 'rel asym', 'max|L-L''|', 'max|Im ev|', ...
            't general', 't sym', 'max|dlambda|');
    for i = 1:size(plan, 1)
        sel = rows(strcmp({rows.name}, plan{i, 1}));
        [~, ord] = sort([sel.M]);
        for r = sel(ord)
            fprintf('%-24s %4d %6d  %10.3e %10.3e %10.3e %8.2fs %8.2fs %11.3e\n', ...
                    r.name, r.M, r.dofs, r.rel_asym, r.max_asym, r.max_imag, ...
                    r.t_general, r.t_sym, max(abs(r.ev_general - r.ev_sym)));
        end
    end

    speedup = sum([rows.t_general]) / sum([rows.t_sym]);
    fprintf(['\nOver the whole table the general EIG costs %.0f s and the ', ...
             'symmetric one %.0f s,\na factor of %.1f.\n'], ...
            sum([rows.t_general]), sum([rows.t_sym]), speedup);
end


function rows = empty_rows()
    rows = struct('name', {}, 'M', {}, 'dofs', {}, 'rel_asym', {}, 'max_asym', {}, ...
                  'pattern_sym', {}, 'issym', {}, 'max_imag', {}, ...
                  't_general', {}, 't_sym', {}, 'ev_general', {}, 'ev_sym', {});
end


function write_cached(path, r)
%WRITE_CACHED Both spectra of one matrix, with everything the table needs.
%
%   Seventeen significant digits: the file is read back in place of the
%   computation, and the differences it is read for are at the last place of a
%   double.
    fid = fopen(path, 'w');
    if fid == -1
        error('check_laplace_matrix_symmetry:cache', ...
            'Could not open %s for writing.', path);
    end
    closer = onCleanup(@() fclose(fid));
    fprintf(fid, ['# Domain: %s (DST Laplace matrix, dense eig, general and ', ...
                  'symmetrised)\n'], r.name);
    fprintf(fid, '# Resolution M = %d, dofs = %d\n', r.M, r.dofs);
    fprintf(fid, '# Asymmetry: relative %.17g, largest entry %.17g\n', ...
            r.rel_asym, r.max_asym);
    fprintf(fid, '# Pattern symmetric: %d, issymmetric: %d\n', ...
            r.pattern_sym, r.issym);
    fprintf(fid, '# Largest imaginary part: %.17g\n', r.max_imag);
    fprintf(fid, '# Computation time: %.4f s general, %.4f s symmetrised\n', ...
            r.t_general, r.t_sym);
    fprintf(fid, '# Eigenvalues: %d\n', numel(r.ev_general));
    fprintf(fid, 'n,lambda_general,lambda_symmetrised\n');
    fprintf(fid, '%d,%.17g,%.17g\n', ...
            [1:numel(r.ev_general); r.ev_general(:).'; r.ev_sym(:).']);
end


function r = read_cached(path)
%READ_CACHED A row back from the cache, empty if there is nothing usable.
%
%   Usable means complete: the header says how many eigenvalues there are and the
%   rows have to be there, so a run interrupted while writing is recomputed
%   rather than read.
    r = [];
    if ~exist(path, 'file')
        return;
    end
    fid = fopen(path, 'r');
    if fid == -1
        return;
    end
    header = {};
    while true
        line = fgetl(fid);
        if ~ischar(line) || isempty(line) || line(1) ~= '#'; break; end
        header{end+1} = line; %#ok<AGROW>
    end
    fclose(fid);
    header = strjoin(header, ' ');

    v = @(pattern) local_token(header, pattern);
    n = v('Eigenvalues:\s*(\d+)');
    if isnan(n)
        return;
    end
    try
        T = readtable(path, 'CommentStyle', '#');
    catch
        return;
    end
    if height(T) ~= n
        return;
    end

    r = struct('name', local_string(header, 'Domain:\s*(\S+)'), ...
               'M', v('M\s*=\s*(\d+)'), 'dofs', v('dofs\s*=\s*(\d+)'), ...
               'rel_asym', v('relative\s*([0-9.eE+-]+)'), ...
               'max_asym', v('largest entry\s*([0-9.eE+-]+)'), ...
               'pattern_sym', v('Pattern symmetric:\s*(\d+)'), ...
               'issym', v('issymmetric:\s*(\d+)'), ...
               'max_imag', v('imaginary part:\s*([0-9.eE+-]+)'), ...
               't_general', v('time:\s*([0-9.eE+-]+)'), ...
               't_sym', v('s general,\s*([0-9.eE+-]+)'), ...
               'ev_general', T.lambda_general, 'ev_sym', T.lambda_symmetrised);
end


function x = local_token(s, pattern)
    tok = regexp(s, pattern, 'tokens', 'once');
    if isempty(tok)
        x = NaN;
    else
        x = str2double(tok{1});
    end
end


function x = local_string(s, pattern)
    tok = regexp(s, pattern, 'tokens', 'once');
    if isempty(tok)
        x = '';
    else
        x = tok{1};
    end
end
